### ISSUE TITLE
**Stack Smashing**

### ISSUE THREAD

**Issue by HaeminJung** [AndrewCarterUK/mnist-neural-network-plain-c#1]
Hi Andrew.

![Screenshot from 2019-06-05 20-56-40](https://user-images.githubusercontent.com/31620852/58954550-72c76f00-87d4-11e9-8db8-931bbd2341e5.png)
I am getting a Stack Smashing Error from gcc.

The code does everything as it should, but does not terminate as it should.
I have figured out the the code is not escaping correctly from the training for loop.

This issue may particularly due to my devices setting(Ubuntu18.04.2).

**Comment by AndrewCarterUK** [comment]
The screenshot suggests you are editing the code and recompiling it, were you getting that error with the code untouched?

If you have been changing it, feel free to push it up to your fork as a new branch and I'll have a look.

**Comment by HaeminJung** [comment]
The original code also produced the same error. I was just messing with the iterration number and printf's to try debug it with ease.

I am taking a look under the hood with gdb but help would be much appreciated :)

**Comment by HaeminJung** [comment]
Andrew, looks like I have found the reason.

Something(the compiler or else) wasn't able to find the file raise.c

After git cloning glibc to the home directory, the code now runs fine.
`sudo git clone git://sourceware.org/git/glibc.git`

I have figured out the fix, but not quite fully grasp what had happened here.
If you do, could you help me with figuring out what had gone wrong, and what had been fixed?

**Comment by dharijanto** [comment]
I encountered the same issue. Here's the culprit:

```diff
--- a/neural_network.c
+++ b/neural_network.c
@@ -120,6 +120,7 @@ float neural_network_training_step(mnist_dataset_t * dataset, neural_network_t *
     memset(&gradient, 0, sizeof(neural_network_gradient_t));

     // Calculate the gradient and the loss by looping through the training set
     for (i = 0, total_loss = 0; i < dataset->size; i++) {
         total_loss += neural_network_gradient_update(&dataset->images[i], network, &gradient, dataset->labels[i]);
     }
@@ -128,7 +129,7 @@ float neural_network_training_step(mnist_dataset_t * dataset, neural_network_t *
     for (i = 0; i < MNIST_LABELS; i++) {
         network->b[i] -= learning_rate * gradient.b_grad[i] / ((float) dataset->size);

-        for (j = 0; j < MNIST_IMAGE_SIZE + 1; j++) {
+        for (j = 0; j < MNIST_IMAGE_SIZE; j++) {
             network->W[i][j] -= learning_rate * gradient.W_grad[i][j] / ((float) dataset->size);
         }
     }
```

**Comment by AndrewCarterUK** [comment]
Thanks for the report and the patch!
