### ISSUE TITLE
About broken link to tensorflow website that describes this project

### ISSUE THREAD

**Issue by dharijanto** [AndrewCarterUK/mnist-neural-network-plain-c#3]
Since the original link on the README file is no longer available, for those who are looking to get documentation of it on the DL-side, it's available here:
https://web.archive.org/web/20180801165522/https://www.tensorflow.org/versions/r1.1/get_started/mnist/beginners

**Comment by AndrewCarterUK** [comment]
Thanks for letting me know and providing me with the archive link.

I have now fixed the broken link and image and added a note referencing that the tutorial has been deleted.
